language: php

# Don't need sudo
sudo: false

# ALL THE VERSIONS
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

# TUrn mbstring.func_overload on and off, because both situations are important
env:
  - MBSTROVERLOAD=0
  - MBSTROVERLOAD=7

# Install the unit test framework we use
before_script:
  - composer install --prefer-source

# Let 'er rip!
script: vendor/bin/phpunit -d mbstring.func_overload=$MBSTROVERLOAD

